global using School.Domain.Entities;
global using OneOf;
global using School.Application.DTOs.Student;
global using School.Application.ErrorHandler;
global using School.Application.Interfaces.IServices;
global using School.Application.Interfaces.IUnitOfWork;
global using Mapster;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;